[package]
name = "qpm_cli"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/QuestPackageManager/QPM.CLI"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Rename binary
[[bin]]
name = "qpm"
path = "src/main.rs"

[features]
default = ["templatr", "network_test"]
templatr = ["dep:templatr"]
network_test = []

[build-dependencies]
vergen = "7"
color-eyre = { version = "0.6", default-features = false }

[dependencies]
#qpm
qpm_package = { git = "https://github.com/QuestPackageManager/QPM.Package.git" }
qpm_qmod = { git = "https://github.com/QuestPackageManager/QPM.Qmod.git" }
qpm_arg_tokenizer = { git = "https://github.com/QuestPackageManager/QPM.arg_tokenizer.git" }
templatr = { git = "https://github.com/QuestPackageManager/templatr.git", optional = true }

# No need for tracing support
color-eyre = { version = "0.6", default-features = false }
# progress bar
pbr = "*" #{ git = "https://github.com/a8m/pb.git" }

git2 = "0.16"

bytes = "*"
reqwest = { version = "0.11", features = [
    "blocking",
    "json",
    "default-tls",
    "gzip",
    "deflate",
    "brotli",
], default-features = false }
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-xml-rs = "0.6"
semver = { version = "1.0", features = ["serde"] }
cursed-semver-parser = { git = "https://github.com/raftario/cursed-semver-parser.git", features = [
    "serde",
] }
pubgrub = "0.2"
owo-colors = "3"
dirs = "4.0.0"
keyring = "1"
zip = "0.6"
walkdir = "2"
symlink = "0.1.0"
fs_extra = "1.2"
itertools = "0.10"
stopwatch = "0.0.7"


[profile.release]
opt-level = 3
lto = true
strip = "symbols"

[profile.dev.package.backtrace]
opt-level = 3
