[package]
name = "qpm_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#qpm
qpm_package = { git = "https://github.com/QuestPackageManager/QPM.Package.git" }

# No need for tracing support
color-eyre = { version = "0.6", default-features = false }

reqwest = { version = "0.11", features = ["blocking", "json"] }
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
semver = { version = "1.0", features = ["serde"] }
cursed-semver-parser = { git = "https://github.com/raftario/cursed-semver-parser.git", features = [
    "serde",
] }
pubgrub = "0.2"
owo-colors = "3"
dirs = "4.0.0"
keyring = "1"
duct = "0.13.5"
zip = "0.6"
remove_dir_all = "0.7"
walkdir = "2"
symlink = "0.1.0"
fs_extra = "1.2"
itertools = "0.10"

[profile.release]
opt-level = 3
lto = true
