# Runs on push to main, basically the "release" version since we don't really do releases (that's bad right)
name: Cargo Release

on:
  release:
    types: published

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            file-name: qpm
            prefix: linux

          - os: macOS-latest
            file-name: qpm
            prefix: macos

          - os: windows-latest
            file-name: qpm.exe
            prefix: windows

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Get libdbus if Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install -y libdbus-1-dev

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Rename build
        run: |
          pwsh -Command Compress-Archive ./target/release/${{matrix.file-name}} -DestinationPath qpm-${{matrix.prefix}}.zip

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            qpm-${{matrix.prefix}}.zip

      # TODO: Move to somewhere else
      - name: Download Inno Setup
        uses: suisei-cn/actions-download-file@v1
        if: ${{matrix.os == 'windows-latest' }}
        with:
          url: https://jrsoftware.org/download.php/is.exe
          target: ../

      - name: Install Inno Setup
        if: ${{matrix.os == 'windows-latest' }}
        run: "../is.exe /VERYSILENT /NORESTART /ALLUSERS"

      - name: Compile Installer
        if: ${{matrix.os == 'windows-latest' }}
        run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" /f installer/installer.iss'

      - name: Artifact Upload
        uses: actions/upload-artifact@v2
        if: ${{matrix.os == 'windows-latest' }}
        with:
          name: qpm-installer.exe
          path: ./installer/qpm-installer.exe
          
      - name: Upload Installer Assets
        if: ${{matrix.os == 'windows-latest' }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            qpm-installer.exe