# Runs on push to main, basically the "release" version since we don't really do releases (that's bad right)
name: Cargo Release

on:
  release:
    types: published

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            file-name: qpm
            prefix: linux-x64
            arch: x64

          - os: macOS-latest
            file-name: qpm
            prefix: macos-x64
            arch: x64

          - os: windows-latest
            file-name: qpm.exe
            prefix: windows-x64
            arch: x64

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Get libdbus if Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install -y libdbus-1-dev

      - name: Cargo test
        run: |
          cargo test

      - name: Cargo build
        run: |
          cargo build --release

      - name: Compress build
        run: |
          pwsh -Command Compress-Archive ./target/release/${{matrix.file-name}} -DestinationPath qpm-${{matrix.prefix}}.zip

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            qpm-${{matrix.prefix}}.zip

            # MacOS Universal binaries

      - uses: actions-rs/toolchain@v1
        if: ${{matrix.os == 'macos-latest' }}
        with:
          toolchain: nightly
          target: aarch64-apple-darwin

      - name: Double check
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          rustup target add aarch64-apple-darwin 
          rustup show

      - name: Cargo build for aarch64 Mac
        if: ${{matrix.os == 'macos-latest' }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-apple-darwin

      - name: Make M1 Universal binary
        if: ${{matrix.os == 'macos-latest' }}
        run: |
          lipo -create -output qpm target/release/${{matrix.file-name}} target/aarch64-apple-darwin/release/${{matrix.file-name}}
          pwsh -Command Compress-Archive qpm -DestinationPath qpm-macos-universal.zip 

      - name: Artifact Upload
        if: ${{matrix.os == 'macos-latest' }}
        uses: softprops/action-gh-release@v1
        with:
          files: qpm-macos-universal.zip

      # TODO: Move to somewhere else
      - name: Download Inno Setup
        uses: suisei-cn/actions-download-file@v1
        if: ${{matrix.os == 'windows-latest' }}
        with:
          url: https://jrsoftware.org/download.php/is.exe
          target: ../

      - name: Install Inno Setup
        if: ${{matrix.os == 'windows-latest' }}
        run: "../is.exe /VERYSILENT /NORESTART /ALLUSERS"

      - name: Compile Installer
        if: ${{matrix.os == 'windows-latest' }}
        run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" /f installer/installer.iss'

      - name: Upload Installer Assets
        if: ${{matrix.os == 'windows-latest' }}
        uses: softprops/action-gh-release@v1
        with:
          files: ./installer/qpm-installer.exe